name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  cz:
    name: Bump and Changelog
    if: ${{ github.repository != 'liblaf/template' }}
    runs-on: ubuntu-latest
    outputs:
      bump: ${{ steps.bump.outputs.bump }}
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - id: cz
        name: Create Bump and Changelog
        uses: commitizen-tools/commitizen-action@0.16.0
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: body.md
      - id: bump
        name: Detect Changelog
        run: |
          if [[ -n "$(cat "body.md")" ]]; then
            echo "bump = true"
            echo "bump=true" >> "${GITHUB_OUTPUT}"
          else
            echo "bump = false"
            echo "bump=false" >> "${GITHUB_OUTPUT}"
          fi
      - if: ${{ steps.bump.outputs.bump == 'true' }}
        name: Upload Changelog
        uses: actions/upload-artifact@v3.1.2
        with:
          name: changelog
          path: body.md

  publish:
    name: Publish Package
    needs: cz
    if: ${{ needs.cz.outputs.bump == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: git pull
      - name: Publish Package
        uses: ./.github/actions/publish
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
    continue-on-error: true

  build:
    needs: cz
    if: ${{ needs.cz.outputs.bump == 'true' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: git pull
      - id: detect
        name: Detect Build Script
        shell: bash
        run: |
          if [[ -f "scripts/build.sh" ]]; then
            echo "build=true" >> "${GITHUB_OUTPUT}"
          else
            echo "build=false" >> "${GITHUB_OUTPUT}"
          fi
      - if: ${{ steps.detect.outputs.build == 'true' }}
        name: Build Artifacts
        uses: ./.github/actions/build
      - if: ${{ steps.detect.outputs.build == 'true' }}
        name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.os }}
          path: dist/**/*
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    continue-on-error: true

  release:
    needs:
      - cz
      - build
    if: ${{ needs.cz.outputs.bump == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: git pull
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          path: artifacts
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.cz.outputs.version }}
          body_path: artifacts/changelog/body.md
          files: |
            artifacts/macos-latest/**/*
            artifacts/ubuntu-latest/**/*
            artifacts/windows-latest/**/*
