name: Build & Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.11"

jobs:
  detect:
    name: Detect MkDocs Config
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.detect.outputs.docs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: detect
        name: Detect MkDocs Config
        run: |
          if [[ -f "mkdocs.yaml" ]]; then
            echo "docs=true" >> "${GITHUB_OUTPUT}"
            echo ":heavy_check_mark: MkDocs Config Detected" >> "${GITHUB_STEP_SUMMARY}"
          else
            echo "docs=false" >> "${GITHUB_OUTPUT}"
            echo ":x: MkDocs Config Not Found" >> "${GITHUB_STEP_SUMMARY}"
          fi

  docs:
    name: Build & Deploy Documentation
    needs:
      - detect
    if: needs.detect.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install Dependencies
        run: poetry install --with docs --no-interaction
      - name: Build & Deploy Documentation
        run: poetry run mkdocs gh-deploy --no-history
