name: Update LICENSE Copyright Year(s)

on:
  schedule:
    - cron: 0 3 1 1 * # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Update LICENSE Copyright Year
        uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ github.token }}
